### ISSUE TITLE
CPS glitch

### ISSUE THREAD

**Issue by shortc1rcuit** [jcppkkk/BestDealHelper#1]
At the beginning of a new run something goes wrong which causes me to get all acheivements related to cps
![image](https://user-images.githubusercontent.com/55994299/147825860-5ec2e991-cfa8-4e80-9fc0-2d001efed708.png)
![image](https://user-images.githubusercontent.com/55994299/147825899-2c60a765-d0b7-4979-a3f7-2ab77bed607f.png)
It also causes one of the upgrades (it always seems to be one of the mouse/cursor upgrades) to have a CPS-Acceleration ratio of NaN%
![image](https://user-images.githubusercontent.com/55994299/147827015-99329b34-d527-4ced-97cb-5a289ed55430.png)

The acheivements issue does not seem to occur when only CCSE is enabled

**Comment by shortc1rcuit** [comment]
If I enable the mod after the first 3 mouse/cursor upgrades have been purchased then this issue does not occur

**Comment by jcppkkk** [comment]
@shortc1rcuit it should be fixed now, thanks for report!

**Comment by shortc1rcuit** [comment]
Thank you!
