### ISSUE TITLE
Every deal is 0% / Cursor upgrades show up as NaN%

### ISSUE THREAD

**Issue by Samiversal** [jcppkkk/BestDealHelper#2]
After getting the same issue to issue #1, the mod completely broke and every deal is marked as 0%, and the cursor upgrades are marked as NaN%.

I have tried:
-Deleting mod data
-Reinstalling mod
-Putting priority up and down of the mod

NOTE: I am currently going for the "ascending with exactly 1 trillion cookies" achievement and haven't done further testing if that influences it in any way.

![Screenshot_1339](https://user-images.githubusercontent.com/22138639/147854712-cad6e241-2e7b-4b31-986c-564d2bce6b69.png)

**Comment by jcppkkk** [comment]
@Samiversal I just upload a new version. Please restart game and check if this error still happens.

**Comment by jcppkkk** [comment]
feel free to reopen the issue if you still have problem, thanks
